Feature/state california
Voteshield/reggie pull request #83
Opened 2021-10-01 17:03 UTC by Tommi-Tsuruga

2021-10-01 17:27 UTC, zzolo commented
You will need to add the `psutil` dependency to `requirements.txt` and `setup.py`.  This should fix the tests.

2021-11-22 18:43 UTC, cvcotton requested changes
Fix up the county names as I commented, and then this looks ready to merge

2021-11-22 18:43 UTC, cvcotton commented on reggie/configs/data/california.yaml
> +  Alameda: 1
for readability, just make sure to alphabetize these county names

2021-11-22 18:43 UTC, cvcotton commented on reggie/configs/primary_locale_names/county/california.json
> +  { "name": "Orange", "id": "30" },
and also alphabetize these here

2021-11-22 18:43 UTC, cvcotton commented on reggie/configs/primary_locale_names/county/california.json
> +  { "name": "Amador", "id": "03" },
MAKE SURE to remove the leading zero from "03", or the notification emails may be messed up I think

2021-11-24 19:12 UTC, cvcotton approved these changes
cool, thanks!

2021-12-08 21:05 UTC, merged